import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;

public class UniqueLetterString {

    public static void main(String[] args)
    {
        String str = "OBXBYZTNRTJRSHWNWJXQACMCZTXWAJCAGOHOBRMVRJZAFIJYFNPHDIBPJATZXHVTPSELQATXKKXDQPMJSPSQYTDTKFGNYBRXARMWVHMYESBIBMXEFTDOYEFRYYDZZAEDBMFWQJCQTRBLRYGELLUOEKDBPFALUKHAMMBBAASJELBMMXXRKTJXBNCCPDDNZTXHPCLGHYEYLIOQQTZHADRTPGDCYEMIOJHMBQGAFZLYVZUHRWTURHQUCMRJWKQVLRUSRYDDUTEIZXZOKLDSYXIHECRKNFWJMOBUXLHAXABYLAGFWPMKOSLYPCDWMPSWJHAPGMKWJUSVIKEFKFVHJPWOPUPCATNVHYVHWYOITGWQPOPLJUIKJODGQBQRSXMYFFWRIQXVPKBHREKBQOYKNOEJJNRHGKGPOMVEHDJQHEBPWEWLXIHOXYYJJTYRBGREKYPSGXYHHPXKJBAKMKLMMFQMWVMKKXMHLAQVHVECSVCJBRZABLSYCMHSIUJJRESMWECOLLPOOMWZSPDOQHNGTPDJOPLXOIRERFUWIZBYDNLTRJRMJETWYOUCKWHKKGULNTGXBYQDVRLAYYKERCDBGHWTWCFSPNLXXKLLTGEOYVLYBJSNINSQAHKJHDWPDQEFFQTSVAMVCTTURQQPJPTXXKVTSLECEKSBSIXDLSTLZNWMZIXQPBNIMKLAXPUQEAMLSLJOGQWEKLKLBUPOSAWLTJPNWZQIGVPYBHVMVJCSKOHSVNKCPBQVSPHRNZXLVVQYORZFYXBFZGEGPEGNFYNOICRDKXISLZTWWWQVOTXXUKGKQSHBOHZTFORJJHIXKBCIWGTRIQOSHYAWENYYIAFYNIJMJDBTULFJIBHPORJBUNZBBIORFVLEUUHIGOGWPQOQDYLWFAEBFDRZFTQVDVUWAQVTCVFNBYSFQEAYFVXJFUTMOBITHKUTWKHTYXSVWUOZJMTDATAUPZWDZIJEMOSRUUBZURNHMSJSNDWDAGGIVFYTKNZVZNVVDCRANJOAWFMFRLMWXDMUJXDHFVIUDPWCKUIUEZZHNOPIBTAVESYITODWFWLWPDCCKECQVOGRWEEQALVFSXSGBJTBAJSURTLEWDIUYHJWKXZSHVQFUUUSAYTLSNTBNWNLRRHQURJARXZFMRVRCTXMUDWOWRXBDOPWCCVQHUZUOQYZSXWARBAJWEJDTUACADHPTCNOKIRGTKXQHAYMSRFOFDJQKCMPJTLTZEUYFPVKGAUDADXIWGJTNNIDKJJRLIQVLUQOTHWQBBYGWRGEASAVRILFRRFFCWXTQZHSIVAAFZWOXOIWFLIQPPOONJMPWBFPZBIUAICMWVTXXFNEKBBVFBTTMSAZPUIAPSBRYTPWZAJBOVNZKDHUHXVZRQGTATIWDZIVTKADFARDFEFYQQDVMLEJZHTVCTGWEQFDLEJCVIWOYVZIMBMKUPFWDJKTVJZXXDILVXORORSNFDEMEUGDBRHXOEQDRYKHRLMLAFYSDDVYMIRMXRQCDZRXDSPXJXRIEINAWXFGLLOZYYLRYIDFDADJEBXPLPCZGQPZAESADSAYMCUYXUYRMWUKJUMLUTZTUHSPOEHXWGKZBEDNGOBLSTFYODDZWKDVFLFSLCUKDGLSIWAGNCIELBKIEBEBFXXJATLFLDVOVIKLVJLMVSMYTEFWJAYQDBHVDNCZEGRKTMOWQKOFLMEKKCFVLKZCAFQCYDAJCXKCPBPSGALSMJLLBUEXSKDMWCVSEPMOJTBUFKNAAYJVTIARMJDYETIMNDSATWSEMLQOMFTQYHREQGYJWXPXXMQNFJZPMGELJMYEALYWZYMWUTKDYJUDEHHXPKOLGCHRCRUSYKMHBRCHJVRTLDYFASBCFFPORUUVALJHEWONGGOAEOJRHROUQWADRMKBUXBUABRVRFRWTORKKUCAFJCOVGHQSOZTWEXLRYENNIZQYQRGQHMEBGMOHORBIDDUFIDRPGNBDKNOMSMHGOGKZOQBDNMUYMQUFAMMAYVUZMYZNGBESWZHWHZIWCRFSHJHRPEMDXNQJHJMUIIMKORSTZPFXWGXHNLBZHFXEPWKDOSOJZGVTAMUSILABETTDFGUSKVVBVZTQUTZFOPACSJCEEMMJNLVHZKOXJQLSYUURLYNOBZPRWGLNYLNXVFTPBWCZLTTQNDKQCVAHPVMWYOKUTAIEBKSXTCCBOFGYHLXJGWVOWTAAPFJFRFMMXXYHVERRCXRAUEDCLCRNVSXPVVTNMKRFFLBCAFMMFTIRBTQNCMJOPMKPMNELDWVHFCACJYEDCORMXXUOEJJPAYMVLSXLLWLJFPGKFDXNHBWLSVLAPIXLZAPTVNTYYKUYRPXWOPVDYARIXFEIKQYXUWWWQQWCTKRTPYQFEZDDBWLWVJGXZHMECLVXWJAJWGJYIJIZJFEJMQVOSJITNAKKAMIVUMSAOHJSCDUYFUKSZSKYOTGTWHQCEGXWUWELTMKSXUHQBDXTMQKRZDGISSQPVTDAGYMUAMIZGGXBCIDFKUJORGMIKBZJHHJOOGWMCBMUYQIDUNNLYHQJMVNPCNNNQQFGRNPTXXMNQBWPRJJYZKEVDYHVWRLROZZVINUTFTAAABSEJFDWIMDIEYJWTFMSFRLSFHGXCLWEFBWQQHTBDHXBSVLKXTXYKRKENBRASKDFYMDNZBLVPOEMQXLAMKDEKSUNNNQGAPSRTEMCAMKXGFPLEAICIIAHMBVUBZWYICVAUNDDDKBDOARBTNUNMKYGWRDCWSIMDBKUGJYQIVDCAQBENRBJSERLUBDEPDDYXXLJNERXQIBQFCSBKMLBYIMMWISJQBJKEDMAMZQJTWBXGLDARYNVIPFBJCXNPVFDYPOTRHYYMZMNBWEJXKDDBHTZEXHVYNIDJUJGOEEEEDIBBWCRZFXZNWQVILWFDCULRNLZHCPWEGUGHMQXUAWNQYRWXXWYHRIFUXRFEJVWSVQZTETQTUVHXEXPZVAIWTDCNLHBHUZKYCHQNGCHYGPUCAETUOTDZUIOPYCEAAOFNNUNHXNMFSTCJKIKPMNYNNVDDLNIBPHWXMXYRUKZCTMVRDGUJAXWLZVVAICBXKYUGAMFSFOOYOQSBRIAJPBMUCLKOPOGQGDSDXLYWUUAIHQRNJDXMCASCJOLKIENDTDCNEEIRBCYACEBFHTBDXOQECADTLGXURECTFFENBIGOJTOZRPTADXRJKODOHUMAXEVTWRNDKSTOXCQOKJIZAYBJLISWBLAIOMAUQVEBRTGTHFLOLVEVSYQWPMRYPJBIPLWXOMQMJHZZUDCZPMPEZCHATAUGGPZQZKHSQBMXBUIPVBRVZWLVEXGIOCLWIVUJCNVMOHAGJTGDYHYTJCTAMDMAWYIMRBVSUXPKDDGEFBOHUCWCURTYTAEAISAGSRNBNRSJLNBUVCFEUHVHPOVRBLDHSVXGBTPTRDLLFPYSDVLGCVTPRCBKXVEBGFIVABRHGXOWENTTMRFFUHVTTWDTXTVBIFIJWFUWJPAZILOZDQMYFMCVUUOEJPKVMBLRTARNTLLETFFCXKOIANVNHYCIDXQHYKCNNPUTRFXZXDHDCCDDIWTSHOEEQYFKRFABDKEGPLEOPLMTAHFHQGHDFZBFZWECSTTSGKPYEIUOHLJOFPKXBXCAUCDRUQSUAAYKGUOYLNLGZCDUUAJNOXIPTZPUZOCBRWRNBPVNCJDMFVAUZAUBLQUDLGMVSEPZJISZSIGVGNYZRGLOCIZABFTAFLNRBNENIWLAMQVUBYCVRIIVEJGTWISUKOMYJBKFMNVOVZKMVBNQRJCKNDTEAFWCWWNQVYLNZOXJGGATNCFDVPYGETKDDXWXLGBAZIZSKYANTMZTXDOCCEPWPONJWNSIUVVQHNPJSSNMLFLKQIBEYBFGOMPBUZSFZPQETUXKUHXTBJBGBZDGNSLYIRWZABNJLOFBEMICGGIAFTGTNZLIUOBUXBFKWAKKZKSPSCUCZRHRIALIQJSGVBZNDRADQNBIGMPUELDCQWJGTQBJQPCIVVIISKMEWOXNPRZLIOEPPRNLZTIZAMORWUKQBVUYMGCCKZHGGBLLDZFOPUMBUEVBUYPEWKVBOBCPZWBDTXYJUSXKRTVMNUNUMGTTOKAPOHUFPKTPEEBQPEPCMLWBFVQRJMLSHJUTSUBEMQGGHOQJBTPGITIHSTGMAETBQVSJEPIWDORSKDNAVDAZHVCDEMEUJXLFSQLRNVPKRRVISIVEPHREMXZPWKBDKNBIKHKMTDTOUAXEIGMRUJYZBBNDDYDJIVJCSHXHKAVHIZRCZEYOFZFOFBZADGPLTSSSIOMUJERBZLAOOXGFBXYKWTBGOMKHGHVASLBHIYMSXSIEEJDOMNHPBLWJSKFEOYSJOGSAIKVBATFYQKBNYUQYTMXNPUYYUZZULBUVWPEHAXWQNPKYAUUFCNRBYLWOYUIABMSGHWTXYSYKWRSOTCUZMEMJTTLAANDWNUANDCJAVTPIRFPEPZGUGIEZJTKKUJCTXMELZJSRSXJMLJPWFLTRWPFKUVCJUBIFKNHIGCDNSSZPECAUNXVOLDKEVVSPBTKXXMLZKUJITITNWYOVGTNSJMPWABXSBOJIBBVFKEWJMDSXHIGFDJLNWOVCPQFBJQOLJSRUXWTQBSIKQFMXFHABSBMFKTUDGCTPFPSNQVWPLBYVGACBXEAHHTDPOWZWLRGBZIVHGHSXCFYTPWHVZVUGOFHKJHYDJGDUMRWRVAHNYDHORWESMVFMGNLKLBKXORPQBNUGVKATXYYHJEGGNKSCKKLQWWGDIRGCWEYTWOFAOYWFBPZHNZNJSQNGFUXOCAATMLOSIEALMTYEGWDPVXWYITBBZBWSPRVIUEAYYMWGUOMDBEMIVYAADGLPLEFUSRAKDWZAGUVZXXODDTIYPHJZRAGQKFLDMUFMWFWQTVUYEGWMNVZHHQUJQBXHYFJHMCZXUUQCLKVXFFZYYZIOEEDFUWWBCBYXPQWGIUMMJKBOTZQORZQANBRIUATTHVJJQAMVVBJJTCDAVJXXTAHRFBGIMDFROFZBLJJMXKCRDBPJNUIHZICKIYPALHTIZZGUGZIYBCISBWWOKKEXEVVESNHJHANMQBANGTIZNZNSNWUOHYOSLQDVUXSOJBZDQPCPMXCJUSSBNMVGDPYVDFQKXRAXFSTCPKPNOYDFQPYRHKNJSEOJLEKLFYQJNIPWQYXXRLTAFRDGLZZKVXKOLZSHUIUOCBPFIWLQGGJBUSVXGHEPJRMLTGSNZAENASTJXKXTYKBSKFTMRPASNZFPTSJVALRZTGPBHFNIVXLGFINPQFHSKFJDRCQSMIHKNLVCMOPUVHZYDECIFSOBWRYWWNZGJKBPHHSQKDVTYKQECVNQHQZSTFKMSSJKFPYWUDRCSWULZNCWSZYOOQZRTDZBZIFFHPTNTPXXMVIYTBLLAJKYSROPNYSPGZJIPVKUEJYEOKWCJDKOOPJJYCFVJJCVKBXPMSJVRWYXAVZTWHIVKDPTWJCWMVNXXOBGHWAEAUVXGERQSSCYTBOKDBLLTMKTBMTNRRFSRBEGTLJVKGHJLKWILDAFBNCUATWSRISXHMKOZHKLYSMNNTLGNHEPVVEZFQIVVOPLCWJQXWGTBWOLFZBABYZSNVQAJOIYVVUMYWBBCFMGZJDFSSKLWMTVQZHXIRSJZVSYNNJADBLRJVKFEPNAKCKIPJKBCBDRKKZHDKWZVHSSDMHQFBMLRPQREOKWOJGHUUXSJDQUCPOHIENFLMPYMXYKWFZMOHNGKIOWTCCUHEWPDULSTGZQVDDFYZERWSFAQRLTVVPJCBFDWRJAHPBUSLYIZDTQUNSDCLCCSRAIWRTZVXRBSDEBQOCIIIFQNFLPBWCYMXRJZMMTKNXIQGGSIPPWZKACUDORURRTXDUUDJYIZUPYZNXKTGFWOFIFLEHHDQMTPCKJIEEFHXACBIKNJKCQXCWICSBXTRJEQKRKICXXXMOKIJHORUYCTWBXCFLCEMSOYSNLPHZVSSLEISJQEDTJRKPEQUEHOMNTNXULZDQPGORLXODGRHBFXMNCXOLABLUWNSKXYKEMFYEITKTPISSOOIPWHQHGHTACFTEYVDAHAERYBFHYYSRIUUNAALMGHPPREPAVSEWKFXZJVTTITPVLPUSMTREZIASYOHSMMPNFTUGMLLOTSEZSGLUZWVDMJPRDUQMLDRLZYGEDPDFXOKMHODGYDIEMUFZDWRLIYDRILPXREJOMNAPRJQCAPTYYMENVXFZUTQGVPVHZWUEXDOUURUJZXZEBOKTNBAWSIIYVENXNGZSCIQFCUSKYEIFSTVRCBULDJTBEPNXSKHLMAFJCTPJTGXIAOLHMIKVNYNNZQGUJRFBIHVCRTWWOFSGCULSCQURUUKNLWMMKKZBGNTVBJEUDPPFMXXQQWDBXVWMEBESGPDOIBOSYELQSPWBXHXUSOHXWZZDZHUBUPBKVFTSBMHKGHOKBNPFOTWEBYNPMIOANGOQYPHZMDSZFBPYSJHRJOUWMYESWKJKNSHQDJWJOGXGQSBSXRGIUBYWJLKNRRIFXXIRIEBUONMNHMXDYLRKLSSYXQPXYILPOGSVDYTNZSFQPTFFCYEDOCRMLCAFMNRJASUVCSPWGXHFBSHRCCDPJMHFBRALIYKIIFYBMYIAAPYQSGKULURNXOTQAMNEGPNGDOZHXVUPDXJUQTQJABQQTFTZVBCYWYIBOVMEMCOEHZVYEQWHLZBBGOLVRYBGOVLQLAAQPTIXMEADKAZTFPEKMFVBCERXHHBEHUZJELDOMCHPZIWHLTVDMBJUYSYXBIABEUKSTDTMLREYPLJBBNEKPUGAFPOJQTLPCQRICFOZTUQXGYTEKHDEVFFTGWCJAUVDEMMYJQCBWPXUXCAZIUEBJYWSLZXKSHQDBHBPUESKRPDDLJJNXNCEFOZOYQWIJBMJSOFGWFHXFZGMZTQUGZJPYGIUGYBFSFMMIYUWTDIWNFMMXVJITFKCVBQRMEMRKKSBDUDHVWOPCAKCHVYVTIKSQVUOTZNFIEOPTMAWBXTOZXHZHXYKUYXSRPBCQUVETWJESIKMIFYNRENQDURSWORALUSZDPEYPESLFYCFDKTZRETDAQIWXRJWGFKKKJYPWSPZRQODTJHHHHPGBDGQPDHOVXDOIITNVQDZQVSNCDAWFLSBNLDOVKNMEBDMETONQDGNVHBFFZWJJXODMAESGLUSLTTEXJBBGCLDPGJZDVFUWJFADPTZYHBWWWIXZREMWTGOCXARXJFWMPNBSYQHWYUWGUVTEFQLPWFPMIYMBYYMPIWBDKXDVWKYEZYOUOUAQHNBGGHDOLTSGNSDIDQWWCHBMGWOVBTGIZABGAPKLHEVYWJKMEVERRAYEKIJCCAIMERANKNDDFDEJICLLMRTHQWCMOZQEZZYZVQKMFUYQSWMGAVESECMLBWNFFKUTXMMULJUMEGJVNHRFWMAEVUVLTMPNWKZJZZBOGNJVQWCBQHYGNYSCHDVMIQIWJWPCJRELXZIIXOOBUUZBYMFYJLKPEACBSMROLPSOBZHWEFXDKJMIPNEMKLFCRAIXTIMEGGTRGYHATLQPCLWRJFQMOHKNHBJRGZVGSRJZDEPFCONBKQCZWTZSEMDUDIJWMNQTHULBOQCUMNFXIALANSFTMKVXEFXJIEOBCBMHBNHJAJHPZCHGXEGEILGYAUROOUCODQVZZAIILGDWRLEQDJODAEVLXSDCVYETZOLSARQCIZCOPLXZDTCUOOXURJDCRAAKCNNTQAHBFWZDZDUNXTXZPVMSENTXYTPOBGPNAHJRKRLDATFBJVWPMHXZMJLSHSRLMZZZZIVDFWBJJPPZDPZUYYVBQZQQGQZFOJOQVUGOEUSDNQDRKVQKBPFBFDXTCTCCWCEJNYGEQJAQZLEJRBVOXIXNUVERKFORUUYQEGIZWMWNQWROMHWJVPOTOLXDZOMATYNKIUONFEJXBUBRAMQKTGERCTAVFTNSBLGCSVEVUOGIXHCPJWAWFZCABBQINTFHMCUNHFTPBJGGNMKUVMRZHVFGPUZEUSSFFDCAFPMBVXAXJSBREPBVRVZPPZWQEFIPZYMTPARCHGTMGGQBKUQSUDWSUYYXTRQLBKSIOIIBUJLAUWHRLPMOVCEECILYTNINLZFQTVDNEIIBZQHYIXAMVUCUGEZFIBSKNPBCLJSZZLIBJCIZTZDIQTFXSVYTIYIHEHLIWIQQUCXLIBHIATBYUVKQAZFTWJXWTWDSQCMTIQMGWZNUHGLFKPVVXHXOIRAOHCKICPKMPUXZMJFNUTTXMPPVDGAJRQGMLPXKRUWGNMJMEQWRYDPDNCBXNGIFERQFIIMGRKHWPCLKZGXFMYJDDSHQEIGAKSBQHXONTPXUUXBSTGOZDESOREQUKRHRFJIOJBXPUWTSUFFOBGLMDDKKHWRAJOGPJEHPOOHJXUVMQSFDDOHVWNBDGTHMAIQGBNRAGQNSJTLDJWVWBLVKLPXROAQZDTZRFFGKGFVOZDQODTBLLSMIPEWJAOFGTWHBESPGGKSRMZZRIEXTKIMEIZWUIEWCQLTPKSLFBLKIOWSBUBSJVZXODSRQUZXXHZSFJVBDLAJAKQTAWHPBRXVMQXGNGEVJFDMNUPXGGZRYGYWCZVDVNXUIWTUMNZGCUKMQVRNXSBGYHNBZHEDSEWSSSSHBCFJJZFYBNORJEGPFLPCIGWJAZIBZITVFJVRNXBWZKEPLBQSRVJESPFHNITENBBJKUNGHZSQHSMEBZJMWSXRZBFNFJTQKPAGNAKMIEAIZTUPHCYEWCIZKIZRSIHDRMOEAEZUNPSXVHQPRTDESTKSIHNIUNCJLKCFQTJTZDQIKBJLNUVJKSDXSDGCPSHEDTXCBZWAHFAXWTGXYIMNXNGXNDWTZNLZLQHGCWQDJLMHZDUYONQACSTHEXUIPDRKSGMBDGMILLNFMMYBJVYCOKWNAEDMRJNRWLKAUUHBVROWIMQLSXBIYMNMUDSWMWJPDZEDCCFNQEIQUZBXQNWQMHGPAFCJJIBCSSPVGYLVJGFWWSZBTLZIXBQOZCPAPVCURCPSEDEOBCDQRRNNWXAYVBVGNIVYSNJHHDPFQZSFTIMCYNIXJIQIZZRJYWZKSXOQZUCALDWIJXJQENIWDYWBXJVESRQTOEEKFMEJCKTBMOYVEQQAANECKLFBAQCUCMKBKFYKFYVOBBGCQZCKTTQTQHRYTZHEWKGDDBGBOSHSMWFMIETKJJRNNSVSCLBURNDHYEXJBFWKAEHDKDUHHJSRCGOECWVUASDSRGSAQRVWCFGSMXBEVIYHQENCCGOXAZESHJIJMXJWJOJQRJGKFIUBVALMDIGDUMAEXWQANDGCJNCAOIYOJDQPCTKHLJXJDTXNLIYOKTBWJXGGGERIMPZPISEOMSPQJOPVOVQJHAXIAMNNYTJNRKTVEARVGQYHNSGXGCYCESNKHZXDPOBDZKPRIBIPRHCRYOIHZBRFDUOOGGFFSGJPAKTBZBYIEPVBIKNBEFTVNHAFFXJHROVXTNWOJYGFZEHUHJGBCQCSQYTJBDINYWEUXQHCWFLVITTSGWGHLWVRUBJCVAHBUBOBYQDDEIZMRLRAZZTIXXSGVOGNMOBFQUFSCCEZKOGOGJFDVWPWRTNBGBJZERXBSEZYPJDVWUEPGIKZZBAAITXSMKSDOUYTOJMBEEUPNVKIWBFDZSDYNOYROVCDOAYEAOGCDQYAIQWUJHGRUWYDNDPTCIHFYKRFBBBQOCDIUBWMWSKRKBIRPUNGMJQVCKBOWBWFZKZHSXGHBNHSEAGSUSZYEVKFIJZGJHKTWEAFVZVQVCVDCRJGJQJYLLUBQAXWGSTGSZXOXMOETCLXKAUWFXVBRNMIXBOSHDMABWACJFRXZGJUNTFNNBLYQJOTXIIHZUPEJGTKDPKTVAAJPHUGOZJTZJCWOLERRGGIXUJRWGAMRTDOWVLKJYOHCUYBJVTKDKCAYDEMNJGPRBYAOVUICGGEDNSAGFPVRSRSNTCURXQ";//"abc";//"aaa";//"\"ANQPLXSKXCKHBQBLVTYYOCQWDAXSIRVIGYRSMPDQGVYYQBVYSREIEZLUYJLQSHKHTTFJXYEZSLLQUXORLRXTGDYDEZLZBPADDQJJPFUCYTKDMMBJYWGTKJCNZYFOURGUZPFFHTAHWYHYXWCMUSVMOFBNHGVZVEYCIZJCEAGVKDTTUHDIVKWTQUTNJAFZSVVRKEHCQYXPDMQLINQJOXVESOLSBYKUHWPHMJODDXTRURBETDAHZXMLHKXHVOVBHCCYXFZELOBJQOPIGDXMJITWKDFBGMOGGVLZMLJTJBJHGRQBNDIYEXSGAAAVRZMXXVRKMBVYVVICPCAFWSCVERPDSMBVPJMWKPCQZLGEFMWHFLCTVIWHYTGMJZSDJUVTWWYUPBXHCMGUTBIWYRUKEFZIMJBDCUJJJLXBNDBAYSBHYULQWNJDZIONTMBSDFSXZTOMUBWBYVPHTJMVUUAHZXSZYJIVTTAUQCFIMIYMFKJFMWDGSCEPYBWDJOJJKKNWOSPOGZNVTYZIZGFOYLDZAYOFBJQJPKUVOSOHADJXJQTRYGZDGVXQCBGVMNKISKHAGEQDZXBNLFIVYHHLTPZKYWEXODOIIZHEODLWTAMNCELNJHYTBWOZGNHQDVDPSYIPUAYDJSOGSXUQFZYLGPYKOTUKIFGPWFJXVVNECBVDYZGOJJUMGBYUZVLLXWFIOLENQPGSDLGUAXZZTFNYQTNBBBBRQHBFQCDHPOALXHAMYFBPRMUYANOANQOPGHROVEVSPAFIQMDTUXJIAAZOKYSKUNDKDYZDQDNVYELELJWMNWNOSGPXOSWPLVWILCORCWECXHYUJEOGUEHCTAOVVIZODZSCFRDIUTCFIYNYMQMWCCPPOQGPQVQIPSMWZKRVNANFLVHJCEMAHEVSNMSXDSMGPZXERJUMQQMVRNFJPQZYHYENLPENMITCABAKWOUIXMRHXXBFAYPBZBBZSMGWROPULVNQQNUGSRVKPIDSBLZDUKZJPQHBBYBUWWJAUSNLLJMZKJVIUYGDMRSEJDZGAQFXKYHNIXWGVWSOXXZVLROKOWJHORIPWKMJCFFJRXKYRRZKDGSIBXGHAQOGBHOQAPXNAPRDIVRJUSAPRPQPUZAYUKLLKIEAARPLXFCOZPPYOFDLOWVQUHOFNVPRLICTLGAKSEUMFQLYBVUCRPVUZWGBSVZRUMWDCFDRLDHCMCUAHIOCMNXIVQRRCYVCMOQSVWSFRSUWOPKXYCOUGREXYFPMZLWQYCSBCHWWLRDNREIJRDHNNSSJKCAGTNDJEANZEBMVOZYOBEOCPUERGUAAEQAUODGSWILWIWCXGJIJTAUIMNYKBPDWLKDVLTZLKWATQLDAGHQRMZPKRAVAUOMJFBXVRBZIFDXTUFSZJKRGXODQAVVOPISYGKPPYTRZVIOQLECHJIXVTPGJSGPEOABAVSVJWIWOBYCMSYCNVOBHJLNEXIXFFGOGRXATDWDILHVCSBKZIOPJWYXXMOXOYUAFVNCEEYCFQIWXHPTTBKBHOXEARPWFJZFSLGSHPXRKWYRRBMWIMRJYBDKADUFRAKMSEDVIGHGFYDKYOFPDHKZJWYCBIDCLEWWMRUACJBXYJWELWIVDAGOIUDMVAVUNUYXLXBCMCRURQKSFDJTNGBWWLKWJHNLPGEKDHTUJLKZFGVJLEXQHXSCNMYNKCEEBENZKRWDOPFKWNETKJGMCFBOLGTEVZVFODVILOSHKIFUIAOVBQUVIBNYNOVTCMLMKZARFPGKVGOHTJWCIMWMFEQIWZXMZNJYUFIMVBNIIVJCSMOZRLZTARCWJEPNYKFVHKEZGLKHMNQKPVJUTYQWYPWZUDZLZYZQIIXXEYGDLYAQSUGKSUYKISXACOPTKPOKNBYKGLUXUWZORPPHFHUXZADQFYVLXNLGOEUBPOHJTEASMLTYDVHGHTVNMREQXAHREOUYCABQJUPRAMTSUUEKTBVHZJERCMPCJOPCHCXHAJHRJJHKVALBVUCNGYJFQZOLTAEVRYJHFIVRLGJSCRCLMNBKMSGODBJSPYWBVYSGJJCVHYVZKOJJEUTTOHUFLQGVNOAJRJKYHAVLRCZSBRXULLHHRDNXNHMUATVQEITYULMAABELBALIMCTROOOXWISOTMVXPVLXBEIQHBFCWCCNQJHDCQQWBYPLQEZFTNKAEPCDYBKPTEEJQIPZUDJVIYTSLOBZHWVJQPMKPUDIAQPUNVOJSXETBYGXELJEXMIAEBPOGDIHZJBZFTBYHVKZRASHEJAIDBJDJVTQTGVAZQOIIUGTSPZLXVTOINRKWYXPWJQEHPNRPXIIVJVKNOVDHWFJVAFYAVPLEYOIHTRCOLENPRCIOHRXZKHULJUJBIWTJHNGNQNCPCVDHWMDYHXFWERSRIGEQPGYMHGBALRKGQHDMZUCXSIMHFQMUONSBWSWFWYYIBIHNNKBHRZOCRUIXHTYMJRJJTPNPEFZGWQTRUBGNDXQRFFPMKERLLABHCYRFKESSVOZMTTZHOPEZHYWYCUTZIXVOKLVOOJGKDSLJXQJOHYODMULNQSSHDPPSOXXHYJLFFCELAZCNQDIMSQXOZZAPRNKPUSMFWEVQOPAZFGUVXWDALUERVAYLGVSKQIXLGZABTWYQXEXXTHJRDGMCMKUVDOVGMAWUXAQWJNARZDLOBYJKNNSYRXYGACWVOCEJBLFWNFKICAABTPLAOHXNTZEVGFTBLPPPSRAWGXWJINLBRYHKEDMHWLJFRNNFHRVFMSXQLZNXZWMTYILMHGJFGQDVPDLNULNRLTJTPTZFHRHKCWTDVSALFHFSOYTVAKEXSTRSJBLWONWIBLQAKHZIKEXBCQJLFPYNWUEFPMYPYEXMPEUHJUGDEHXLIPRRUCCTDESWKBJCXWMLDQFRNAGWUVOMDODJHNVWXCHSOBYWJWRFUDTIEUQCPQZIBMTCEXWUNWOWWYEBWCNESXWRJAKLKRHXGNWIKABZCUJYKWSFWOULPBESWXJGBWTGTXKEGFYVQSEDAPRZMRQRGVQLXLYAFDNTGRNZOKVMNWEIBUTGRQBIWXGWZCFETVIREYLYHBOWWMKTOFLLEDUJDWHHORAYOJKMWHEKITSRSISQCRZJBRFQAACFIVSQDKAYKODPSZRVHTNWDMCUZFDXHLSCJHOCOARYPPJYEPEJCXJFVRCXLLBAXGHHPMNRDPRHIXSQZTALRRBNJJDZRLIXSPOCXJCCGMKBRIKATUXPNTOGCWVMGPJBYTASTCILOBIQQLXHXDFFIGODHSTSDPGEULNORQVUMVXGSGDUXHPEGJINGNOECJHDYQHYFLEFNNWRFAWMSCLBPJEQAPNMRFLZTFIDCWGRXHZPTIYUFAWCNOENOMCVWARWRWKWKLHRPMCFYBUPQWLUMHAHXKONYZXLAXHIFYCNVZKZGGLOBABZHOOBCXQOBNINOHNPLZUUQEQCBTBAMIQGHBYJUQHGRVIQMMNZKBGCXESUEWWVZIRTGIVEUGPNGYVQQGCXXCUZAGXVAPNASAWUJJTTUOXDYGDTFITAEHLAOMCNZYMAUOMVKFXIIDEYCBAORYASRMBRBORPXBZPOELRVDMAFRAGJSGYLZNOWFAOIMDLXZZVLQFQNCDAUKJEMGLPRCSICFPFDXMGFKFARZDDEDYFSQNDOOGORVYDQNULKEQXWDJJTNEGSYJWYKVWGPFTVJOUWYZSCCUBOFQSILDGFNZCKLJGIXPFGHXCQTQUCKWCGBFMVUKXDUVYQYHEYORYNWYVPOORSYJKLVLLUVNMRLYWWIKFGCDYFTWYQHPOYDUNADPFLGPIPDAOHUUFWCSKXCXBBEROLLNGVOMTORHBWEYOKQIBOMAMLULLBHIUIUJGVWVURCDVHZDKBEFRPPYTLJBVEZQKJZKVMNCNCVRFQVPIBMAZDUJVTDQICGBYPZVADZSIFBAOXWPZXBBKUABAVMWTYVKHZCWMUROMHKJEXYJMHZYCMOKRVAQJWBPMPQVBEMBOPANBMNZFVUERPDESFJUPNFUVGLZCTDUOOEVGWHSLSLVXROEPYROWKGGIVXJYNKQXAYAOXNTJXRAVMZUVVLQWVUHHLFDVQOVOBYURPCBADGNYHEEAWFHNKSQAHCTFDEELSZGTJAELREGYGUIWPESFBVEQDLEVZWDOLYFPRCFPOBENHVLBATQXIDTKCQLROKMJFLAKCFGRVZAICEVJVVOCTTGARXGZIAQEVPEHOZDZOCJQSOHZDRTDFDTLVQTRMQJUZZMWYEBNCDLPXVIZAZSEPMOEBAYZZTWNXZBFHKACIUWFXAZSJTTPOJTIUMOMVWGWLWAMDALRGMAHGYPWLACJXCUETTHMYRABOTTEDCJAFLBTJKLQVWWEDUBTROZAZVREQQHGKBIDWRSAXGTHHFRJRYHVWUIHHVXMUKDYOHOYMGGRUUXICOCHOYVMUAUQLBSZTUPJXSDQYRSGIUZWYINOLDNNZZZMCTJJTPWKIXECTQALOMFWBWFQBFTUILTPTNWWFUSHVAWHCQSIUYUYUMEOEHHFATHMIGRMALWIACTSFOADRRJRVNHAIIVIBWVAUTGBKUXOFCIRIBLYEYNJJRWRJDGYUVHMICFZJSUXCMCHBIBDMKJMJVBQOQWWQANXVMOGKMHNJFLQNOOBMLDMSROITEAJKJQOPLNUGOYJOFBOBRUUCLSRIAJIUYMAZTUJYQSHXWHVQIETWUAQGTPAZGPILJSDDOUFOYXKKLFMBXHZYDRCTLPHRYRWCELWQUHLQPMRQAXGBFVWTNRVBAPTFJKODHHIVBWCLSPJLDXAXWIPWLFGLBGHDULRQXDCPXAPTEZOGTTQATIWUJHWZPUVEURNWSJDAQQNPFYUVIHGAGJYQNKMMWMSYXQJZFZVLNZZOWXRJKSOHUBKAOAEUKVCOMVBMCSLUMNNDINDHFUUMHIEOXXXSHPYGAIVFPBJKKSDPXAOCDYPPYJZTAWVBQKBIOORFJFETOWRBLCYCFNXVJRIOBXBYZTNRTJRSHWNWJXQACMCZTXWAJCAGOHOBRMVRJZAFIJYFNPHDIBPJATZXHVTPSELQATXKKXDQPMJSPSQYTDTKFGNYBRXARMWVHMYESBIBMXEFTDOYEFRYYDZZAEDBMFWQJCQTRBLRYGELLUOEKDBPFALUKHAMMBBAASJELBMMXXRKTJXBNCCPDDNZTXHPCLGHYEYLIOQQTZHADRTPGDCYEMIOJHMBQGAFZLYVZUHRWTURHQUCMRJWKQVLRUSRYDDUTEIZXZOKLDSYXIHECRKNFWJMOBUXLHAXABYLAGFWPMKOSLYPCDWMPSWJHAPGMKWJUSVIKEFKFVHJPWOPUPCATNVHYVHWYOITGWQPOPLJUIKJODGQBQRSXMYFFWRIQXVPKBHREKBQOYKNOEJJNRHGKGPOMVEHDJQHEBPWEWLXIHOXYYJJTYRBGREKYPSGXYHHPXKJBAKMKLMMFQMWVMKKXMHLAQVHVECSVCJBRZABLSYCMHSIUJJRESMWECOLLPOOMWZSPDOQHNGTPDJOPLXOIRERFUWIZBYDNLTRJRMJETWYOUCKWHKKGULNTGXBYQDVRLAYYKERCDBGHWTWCFSPNLXXKLLTGEOYVLYBJSNINSQAHKJHDWPDQEFFQTSVAMVCTTURQQPJPTXXKVTSLECEKSBSIXDLSTLZNWMZIXQPBNIMKLAXPUQEAMLSLJOGQWEKLKLBUPOSAWLTJPNWZQIGVPYBHVMVJCSKOHSVNKCPBQVSPHRNZXLVVQYORZFYXBFZGEGPEGNFYNOICRDKXISLZTWWWQVOTXXUKGKQSHBOHZTFORJJHIXKBCIWGTRIQOSHYAWENYYIAFYNIJMJDBTULFJIBHPORJBUNZBBIORFVLEUUHIGOGWPQOQDYLWFAEBFDRZFTQVDVUWAQVTCVFNBYSFQEAYFVXJFUTMOBITHKUTWKHTYXSVWUOZJMTDATAUPZWDZIJEMOSRUUBZURNHMSJSNDWDAGGIVFYTKNZVZNVVDCRANJOAWFMFRLMWXDMUJXDHFVIUDPWCKUIUEZZHNOPIBTAVESYITODWFWLWPDCCKECQVOGRWEEQALVFSXSGBJTBAJSURTLEWDIUYHJWKXZSHVQFUUUSAYTLSNTBNWNLRRHQURJARXZFMRVRCTXMUDWOWRXBDOPWCCVQHUZUOQYZSXWARBAJWEJDTUACADHPTCNOKIRGTKXQHAYMSRFOFDJQKCMPJTLTZEUYFPVKGAUDADXIWGJTNNIDKJJRLIQVLUQOTHWQBBYGWRGEASAVRILFRRFFCWXTQZHSIVAAFZWOXOIWFLIQPPOONJMPWBFPZBIUAICMWVTXXFNEKBBVFBTTMSAZPUIAPSBRYTPWZAJBOVNZKDHUHXVZRQGTATIWDZIVTKADFARDFEFYQQDVMLEJZHTVCTGWEQFDLEJCVIWOYVZIMBMKUPFWDJKTVJZXXDILVXORORSNFDEMEUGDBRHXOEQDRYKHRLMLAFYSDDVYMIRMXRQCDZRXDSPXJXRIEINAWXFGLLOZYYLRYIDFDADJEBXPLPCZGQPZAESADSAYMCUYXUYRMWUKJUMLUTZTUHSPOEHXWGKZBEDNGOBLSTFYODDZWKDVFLFSLCUKDGLSIWAGNCIELBKIEBEBFXXJATLFLDVOVIKLVJLMVSMYTEFWJAYQDBHVDNCZEGRKTMOWQKOFLMEKKCFVLKZCAFQCYDAJCXKCPBPSGALSMJLLBUEXSKDMWCVSEPMOJTBUFKNAAYJVTIARMJDYETIMNDSATWSEMLQOMFTQYHREQGYJWXPXXMQNFJZPMGELJMYEALYWZYMWUTKDYJUDEHHXPKOLGCHRCRUSYKMHBRCHJVRTLDYFASBCFFPORUUVALJHEWONGGOAEOJRHROUQWADRMKBUXBUABRVRFRWTORKKUCAFJCOVGHQSOZTWEXLRYENNIZQYQRGQHMEBGMOHORBIDDUFIDRPGNBDKNOMSMHGOGKZOQBDNMUYMQUFAMMAYVUZMYZNGBESWZHWHZIWCRFSHJHRPEMDXNQJHJMUIIMKORSTZPFXWGXHNLBZHFXEPWKDOSOJZGVTAMUSILABETTDFGUSKVVBVZTQUTZFOPACSJCEEMMJNLVHZKOXJQLSYUURLYNOBZPRWGLNYLNXVFTPBWCZLTTQNDKQCVAHPVMWYOKUTAIEBKSXTCCBOFGYHLXJGWVOWTAAPFJFRFMMXXYHVERRCXRAUEDCLCRNVSXPVVTNMKRFFLBCAFMMFTIRBTQNCMJOPMKPMNELDWVHFCACJYEDCORMXXUOEJJPAYMVLSXLLWLJFPGKFDXNHBWLSVLAPIXLZAPTVNTYYKUYRPXWOPVDYARIXFEIKQYXUWWWQQWCTKRTPYQFEZDDBWLWVJGXZHMECLVXWJAJWGJYIJIZJFEJMQVOSJITNAKKAMIVUMSAOHJSCDUYFUKSZSKYOTGTWHQCEGXWUWELTMKSXUHQBDXTMQKRZDGISSQPVTDAGYMUAMIZGGXBCIDFKUJORGMIKBZJHHJOOGWMCBMUYQIDUNNLYHQJMVNPCNNNQQFGRNPTXXMNQBWPRJJYZKEVDYHVWRLROZZVINUTFTAAABSEJFDWIMDIEYJWTFMSFRLSFHGXCLWEFBWQQHTBDHXBSVLKXTXYKRKENBRASKDFYMDNZBLVPOEMQXLAMKDEKSUNNNQGAPSRTEMCAMKXGFPLEAICIIAHMBVUBZWYICVAUNDDDKBDOARBTNUNMKYGWRDCWSIMDBKUGJYQIVDCAQBENRBJSERLUBDEPDDYXXLJNERXQIBQFCSBKMLBYIMMWISJQBJKEDMAMZQJTWBXGLDARYNVIPFBJCXNPVFDYPOTRHYYMZMNBWEJXKDDBHTZEXHVYNIDJUJGOEEEEDIBBWCRZFXZNWQVILWFDCULRNLZHCPWEGUGHMQXUAWNQYRWXXWYHRIFUXRFEJVWSVQZTETQTUVHXEXPZVAIWTDCNLHBHUZKYCHQNGCHYGPUCAETUOTDZUIOPYCEAAOFNNUNHXNMFSTCJKIKPMNYNNVDDLNIBPHWXMXYRUKZCTMVRDGUJAXWLZVVAICBXKYUGAMFSFOOYOQSBRIAJPBMUCLKOPOGQGDSDXLYWUUAIHQRNJDXMCASCJOLKIENDTDCNEEIRBCYACEBFHTBDXOQECADTLGXURECTFFENBIGOJTOZRPTADXRJKODOHUMAXEVTWRNDKSTOXCQOKJIZAYBJLISWBLAIOMAUQVEBRTGTHFLOLVEVSYQWPMRYPJBIPLWXOMQMJHZZUDCZPMPEZCHATAUGGPZQZKHSQBMXBUIPVBRVZWLVEXGIOCLWIVUJCNVMOHAGJTGDYHYTJCTAMDMAWYIMRBVSUXPKDDGEFBOHUCWCURTYTAEAISAGSRNBNRSJLNBUVCFEUHVHPOVRBLDHSVXGBTPTRDLLFPYSDVLGCVTPRCBKXVEBGFIVABRHGXOWENTTMRFFUHVTTWDTXTVBIFIJWFUWJPAZILOZDQMYFMCVUUOEJPKVMBLRTARNTLLETFFCXKOIANVNHYCIDXQHYKCNNPUTRFXZXDHDCCDDIWTSHOEEQYFKRFABDKEGPLEOPLMTAHFHQGHDFZBFZWECSTTSGKPYEIUOHLJOFPKXBXCAUCDRUQSUAAYKGUOYLNLGZCDUUAJNOXIPTZPUZOCBRWRNBPVNCJDMFVAUZAUBLQUDLGMVSEPZJISZSIGVGNYZRGLOCIZABFTAFLNRBNENIWLAMQVUBYCVRIIVEJGTWISUKOMYJBKFMNVOVZKMVBNQRJCKNDTEAFWCWWNQVYLNZOXJGGATNCFDVPYGETKDDXWXLGBAZIZSKYANTMZTXDOCCEPWPONJWNSIUVVQHNPJSSNMLFLKQIBEYBFGOMPBUZSFZPQETUXKUHXTBJBGBZDGNSLYIRWZABNJLOFBEMICGGIAFTGTNZLIUOBUXBFKWAKKZKSPSCUCZRHRIALIQJSGVBZNDRADQNBIGMPUELDCQWJGTQBJQPCIVVIISKMEWOXNPRZLIOEPPRNLZTIZAMORWUKQBVUYMGCCKZHGGBLLDZFOPUMBUEVBUYPEWKVBOBCPZWBDTXYJUSXKRTVMNUNUMGTTOKAPOHUFPKTPEEBQPEPCMLWBFVQRJMLSHJUTSUBEMQGGHOQJBTPGITIHSTGMAETBQVSJEPIWDORSKDNAVDAZHVCDEMEUJXLFSQLRNVPKRRVISIVEPHREMXZPWKBDKNBIKHKMTDTOUAXEIGMRUJYZBBNDDYDJIVJCSHXHKAVHIZRCZEYOFZFOFBZADGPLTSSSIOMUJERBZLAOOXGFBXYKWTBGOMKHGHVASLBHIYMSXSIEEJDOMNHPBLWJSKFEOYSJOGSAIKVBATFYQKBNYUQYTMXNPUYYUZZULBUVWPEHAXWQNPKYAUUFCNRBYLWOYUIABMSGHWTXYSYKWRSOTCUZMEMJTTLAANDWNUANDCJAVTPIRFPEPZGUGIEZJTKKUJCTXMELZJSRSXJMLJPWFLTRWPFKUVCJUBIFKNHIGCDNSSZPECAUNXVOLDKEVVSPBTKXXMLZKUJITITNWYOVGTNSJMPWABXSBOJIBBVFKEWJMDSXHIGFDJLNWOVCPQFBJQOLJSRUXWTQBSIKQFMXFHABSBMFKTUDGCTPFPSNQVWPLBYVGACBXEAHHTDPOWZWLRGBZIVHGHSXCFYTPWHVZVUGOFHKJHYDJGDUMRWRVAHNYDHORWESMVFMGNLKLBKXORPQBNUGVKATXYYHJEGGNKSCKKLQWWGDIRGCWEYTWOFAOYWFBPZHNZNJSQNGFUXOCAATMLOSIEALMTYEGWDPVXWYITBBZBWSPRVIUEAYYMWGUOMDBEMIVYAADGLPLEFUSRAKDWZAGUVZXXODDTIYPHJZRAGQKFLDMUFMWFWQTVUYEGWMNVZHHQUJQBXHYFJHMCZXUUQCLKVXFFZYYZIOEEDFUWWBCBYXPQWGIUMMJKBOTZQORZQANBRIUA\"";
        UniqueLetterString obj =  new UniqueLetterString();
        System.out.println(obj.uniqueLetterString(str));
    }

    public int uniqueLetterString(String S) {

        HashMap<Character, List<Integer>> index =  new HashMap<>();
        for(int i=0; i < S.length(); i++)
        {
            char c = S.charAt(i);
            if(index.get(c) != null)
            {
                List<Integer> temp = index.get(c);
                temp.add(i);
            }
            else{
                List<Integer> temp = new ArrayList<Integer>();
                temp.add(i);
                index.put(c,temp);
            }
        }
        long count=0;
        for(List<Integer> temp : index.values())
        {
            for(int i=0; i <temp.size(); i++)
            {
                int prev = i > 0 ? temp.get(i-1) : -1;
                int next = i < temp.size() - 1 ? temp.get(i+1) : S.length();
                count += (temp.get(i) - prev) * (next - temp.get(i));
            }
        }
        return (int) count % 1000000007;
    }

    /*public int uniqueLetterString(String s) {

        if(s.length() == 0)
            return 0;

        int[] map =  new int[255];
        int[][] cMap = new int[s.length()][s.length()];

        char[] arr= s.toCharArray();
        int count  = 0;

        for(int i=0; i<arr.length; i++)
        {

            if(i%2 == 0) {
                for (int j = i; j < arr.length; j++) {

                    // System.out.println(s.substring(i,j+1));
                    map[arr[j]]++;

                    if(j == 0)
                        cMap[i][j] = 1;

                    if( j>0 )
                    {
                      if( map[arr[j]] > 1 )
                            cMap[i][j] = cMap[i][j-1];
                        else
                            cMap[i][j] = 1 + cMap[i][j-1];
                    }
                }
            }
            else{

                if(i > 0)
                    map[arr[i-1]]--;

                for (int j = 0; j < arr.length - i; j++)
                {
                    //System.out.println(s.substring(i,arr.length - k));
                    if(j == 0)
                        cMap[i][arr.length - j - 1] = getUnique(map);

                    if(j > 0)
                    {
                        if(map[arr[arr.length - j - 1]] > 1 && arr[arr.length - j - 1] == arr[arr.length - j ])
                        {
                            cMap[i][arr.length - j - 1] = cMap[i][arr.length - j ];
                        }
                        else if(map[arr[arr.length - j - 1]] == 1&& arr[arr.length - j - 1] == arr[arr.length - j ])
                        {
                            cMap[i][arr.length - j - 1] = cMap[i][arr.length - j ] + 1;
                        }
                        else if(map[arr[arr.length - j - 1]] == 1 && arr[arr.length - j - 1] != arr[arr.length - j ])
                        {
                            cMap[i][arr.length - j - 1] = cMap[i][arr.length - j ] - 1;
                        }
                        else{
                            cMap[i][arr.length - j - 1] = getUnique(map);
                        }

                    }
                    map[arr[arr.length - j - 1]]--;
                }
            }
        }

        for(int i=0; i < s.length(); i++)
        {
            for(int j=0; j < s.length(); j++)
            {
                count = (count + cMap[i][j]) % 1000000007;
            }
        }
        return count;
    }
*/
    private int getUnique(int[] map) {
        int count = 0;
        for(int i=0; i<map.length;i++)
        {
            if(map[i] == 1)
                count++;
        }
        return count;
    }
}
